# -*- coding: utf-8 -*-
"""babaSprites.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbY4fxH9dHzwwbNfMBqoGwKjGIgwSF7M
"""

# if you need to install pillow run following code in command line
# python3 -m pip install --upgrade pip
# python3 -m pip install --upgrade Pillow

from PIL import Image
from os import mkdir
import os

#open sprite sheet
sheet = Image.open('babaSheet.png')

cwd = os.getcwd()
print(cwd)

#cuts out boxes top down first
#bunny right
box = 24 #pixels
left = 0
top = 0
right = 24
bottom = 24

counter = 0
basename = 'sprite_%d.png'

for i in range(5):
  for j in range(3):
    sprite = sheet.crop((left, top, right, bottom))
    top = top + box
    bottom = bottom + box
    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  top = 0
  bottom = box
  left = left + box
  right = right + box
  i+=1

#pastes sprite boxes together horizontally
fullSprite = Image.new('RGBA', (15*box, box))
for i in range(15):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
  
fullSprite.save('bunnyRight.png', 'png')

#cuts out boxes top down first
#bunny up
box = 24 #pixels
left = box * 5
top = 0
right = box * 6
bottom = 24

counter = 0
basename = 'sprite_%d.png'

for i in range(5):
  for j in range(3):
    sprite = sheet.crop((left, top, right, bottom))
    top = top + box
    bottom = bottom + box
    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  top = 0
  bottom = box
  left = left + box
  right = right + box
  i+=1

#pastes sprite boxes together horizontally
fullSprite = Image.new('RGBA', (15*box, box))
for i in range(15):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
  
fullSprite.save('bunnyUp.png', 'png')

#cuts out boxes top down first
#bunny left
box = 24 #pixels
left = box * 10
top = 0
right = box * 11
bottom = 24

counter = 0
basename = 'sprite_%d.png'

for i in range(5):
  for j in range(3):
    sprite = sheet.crop((left, top, right, bottom))
    top = top + box
    bottom = bottom + box
    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  top = 0
  bottom = box
  left = left + box
  right = right + box
  i+=1

#pastes sprite boxes together horizontally
fullSprite = Image.new('RGBA', (15*box, box))
for i in range(15):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
  
fullSprite.save('bunnyLeft.png', 'png')

#cuts out boxes top down first
#bunny down
box = 24 #pixels
left = box * 15
top = 0
right = box * 16
bottom = 24

counter = 0
basename = 'sprite_%d.png'

for i in range(5):
  for j in range(3):
    sprite = sheet.crop((left, top, right, bottom))
    top = top + box
    bottom = bottom + box
    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  top = 0
  bottom = box
  left = left + box
  right = right + box
  i+=1

#pastes sprite boxes together horizontally
fullSprite = Image.new('RGBA', (15*box, box))
for i in range(15):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
  
fullSprite.save('bunnyDown.png', 'png')

"""Words"""

# box = 24 #pixels
# left = 0
# top = box * 27
# right = box
# bottom = box * 28
# counter = 0
# for h in range(32):
#   top = box * 27
#   bottom = box * 28

  
#   basename = 'sprite_%d.png'


#   for j in range(3):
#     sprite = sheet.crop((left, top, right, bottom))
#     top = top + box
#     bottom = bottom + box
#     counter +=1
#     name = basename % counter
#     sprite.save(name)
#     print("Wrote %s" % name)
#     j += 1

#   #pastes sprite boxes together horizontally
#   fullSprite = Image.new('RGBA', (3*box, box))

#   for i in range(3):
#     i += 1
#     fullSprite.paste(Image.open('sprite_'+ str(counter) + '.png'),(0 + ((i*box) - box), 0))

#   fullSprite.save(('/content/word' + str(h+1)+ '.png'), 'png')

#   left = left + box
#   right = right + box
#   h += 1

#AB
box = 24 #pixels
left = 0
top = box * 27
right = box
bottom = box * 28

counter = 0
basename = 'sprite_%d.png'


for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

#pastes sprite boxes together horizontally
fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
  
fullSprite.save('wordAb.png', 'png')

#Algae
box = 24 #pixels
left = box
top = box * 27
right = box * 2
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordAlgae.png', 'png')

#all
box = 24 #pixels
left = box * 2
top = box * 27
right = box * 3
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordAll.png', 'png')

#And
box = 24 #pixels
left = box * 3
top = box * 27
right = box * 4
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordAnd.png', 'png')

#Anni
box = 24 #pixels
left = box * 4
top = box * 27
right = box * 5
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordAnni.png', 'png')

#BA
box = 24 #pixels
left = box * 5
top = box * 27
right = box * 6
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBa.png', 'png')

#Baba
box = 24 #pixels
left = box * 6
top = box * 27
right = box * 7
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBaba.png', 'png')

#Bat
box = 24 #pixels
left = box * 7
top = box * 27
right = box * 8
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBat.png', 'png')

#Belt
box = 24 #pixels
left = box * 8
top = box * 27
right = box * 9
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBelt.png', 'png')

#Bird
box = 24 #pixels
left = box * 9
top = box * 27
right = box * 10
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBird.png', 'png')

#Bog
box = 24 #pixels
left = box * 10
top = box * 27
right = box * 11
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBog.png', 'png')

#Bolt
box = 24 #pixels
left = box * 11
top = box * 27
right = box * 12
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBolt.png', 'png')

#Box
box = 24 #pixels
left = box * 12
top = box * 27
right = box * 13
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBox.png', 'png')

#Brick
box = 24 #pixels
left = box * 13
top = box * 27
right = box * 14
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBrick.png', 'png')

#Bubble
box = 24 #pixels
left = box * 14
top = box * 27
right = box * 15
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBubble.png', 'png')

#Bug
box = 24 #pixels
left = box * 15
top = box * 27
right = box * 16
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBug.png', 'png')

#Cake
box = 24 #pixels
left = box * 16
top = box * 27
right = box * 17
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCake.png', 'png')

#Cash
box = 24 #pixels
left = box * 17
top = box * 27
right = box * 18
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCash.png', 'png')

#cliff
box = 24 #pixels
left = box * 18
top = box * 27
right = box * 19
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCliff.png', 'png')

#Cloud
box = 24 #pixels
left = box * 19
top = box * 27
right = box * 20
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCloud.png', 'png')

#Cog
box = 24 #pixels
left = box * 20
top = box * 27
right = box * 21
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCog.png', 'png')

#Crab
box = 24 #pixels
left = box * 21
top = box * 27
right = box * 22
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCrab.png', 'png')

#cup
box = 24 #pixels
left = box * 22
top = box * 27
right = box * 23
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCup.png', 'png')

#Cursor
box = 24 #pixels
left = box * 23
top = box * 27
right = box * 24
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordCursor.png', 'png')

#Door
box = 24 #pixels
left = box * 24
top = box * 27
right = box * 25
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDoor.png', 'png')

#Dot
box = 24 #pixels
left = box * 25
top = box * 27
right = box * 26
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDot.png', 'png')

#Dust
box = 24 #pixels
left = box * 26
top = box * 27
right = box * 27
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDust.png', 'png')

#Eat
box = 24 #pixels
left = box * 27
top = box * 27
right = box * 28
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordEat.png', 'png')

#Empty
box = 24 #pixels
left = box * 28
top = box * 27
right = box * 29
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordEmpty.png', 'png')

#Facing
box = 24 #pixels
left = box * 29
top = box * 27
right = box * 30
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFacing.png', 'png')

#Fear
box = 24 #pixels
left = box * 30
top = box * 27
right = box * 31
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFear.png', 'png')

#Fence
box = 24 #pixels
left = box * 31
top = box * 27
right = box * 32
bottom = box * 28
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFence.png', 'png')

#Fire
box = 24 #pixels
left = box * 0
top = box * 30
right = box * 1
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFire.png', 'png')

#Flag
box = 24 #pixels
left = box * 1
top = box * 30
right = box * 2
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFlag.png', 'png')

#Flower
box = 24 #pixels
left = box * 2
top = box * 30
right = box * 3
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFlower.png', 'png')

#Foliage
box = 24 #pixels
left = box * 3
top = box * 30
right = box * 4
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFoliage.png', 'png')

#Follow
box = 24 #pixels
left = box * 4
top = box * 30
right = box * 5
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFollow.png', 'png')

#Fruit
box = 24 #pixels
left = box * 5
top = box * 30
right = box * 6
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFruit.png', 'png')

#Fungi
box = 24 #pixels
left = box * 6
top = box * 30
right = box * 7
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFungi.png', 'png')

#Fungus
box = 24 #pixels
left = box * 7
top = box * 30
right = box * 8
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFungus.png', 'png')

#Ghost
box = 24 #pixels
left = box * 8
top = box * 30
right = box * 9
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordGhost.png', 'png')

#Grass
box = 24 #pixels
left = box * 9
top = box * 30
right = box * 10
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordGrass.png', 'png')

#Group
box = 24 #pixels
left = box * 10
top = box * 30
right = box * 11
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordGroup.png', 'png')

#Hand
box = 24 #pixels
left = box * 11
top = box * 30
right = box * 12
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHand.png', 'png')

#Has
box = 24 #pixels
left = box * 12
top = box * 30
right = box * 13
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHas.png', 'png')

#Hedge
box = 24 #pixels
left = box * 13
top = box * 30
right = box * 14
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHedge.png', 'png')

#Husk
box = 24 #pixels
left = box * 14
top = box * 30
right = box * 15
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHusk.png', 'png')

#Ice
box = 24 #pixels
left = box * 15
top = box * 30
right = box * 16
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordIce.png', 'png')

#Idle
box = 24 #pixels
left = box * 16
top = box * 30
right = box * 17
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordIdle.png', 'png')

#Image
box = 24 #pixels
left = box * 17
top = box * 30
right = box * 18
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordImage.png', 'png')

#Is
box = 24 #pixels
left = box * 18
top = box * 30
right = box * 19
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordIs.png', 'png')

#Jelly
box = 24 #pixels
left = box * 19
top = box * 30
right = box * 20
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordJelly.png', 'png')

#KEKE
box = 24 #pixels
left = box * 20
top = box * 30
right = box * 21
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordKeke.png', 'png')

#Key
box = 24 #pixels
left = box * 21
top = box * 30
right = box * 22
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordKey.png', 'png')

#Ladder
box = 24 #pixels
left = box * 22
top = box * 30
right = box * 23
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLadder.png', 'png')

#Leaf
box = 24 #pixels
left = box * 23
top = box * 30
right = box * 24
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLeaf.png', 'png')

#Lava
box = 24 #pixels
left = box * 24
top = box * 30
right = box * 25
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLava.png', 'png')

#Level
box = 24 #pixels
left = box * 25
top = box * 30
right = box * 26
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLevel.png', 'png')

#Line
box = 24 #pixels
left = box * 26
top = box * 30
right = box * 27
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLine.png', 'png')

#Lonely
box = 24 #pixels
left = box * 27
top = box * 30
right = box * 28
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLonely.png', 'png')

#Love
box = 24 #pixels
left = box * 28
top = box * 30
right = box * 29
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLove.png', 'png')

#Make
box = 24 #pixels
left = box * 29
top = box * 30
right = box * 30
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMake.png', 'png')

#Me
box = 24 #pixels
left = box * 30
top = box * 30
right = box * 31
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMe.png', 'png')

#Mono
box = 24 #pixels
left = box * 31
top = box * 30
right = box * 32
bottom = box * 31
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMono.png', 'png')

#Near
box = 24 #pixels
left = box * 0
top = box * 33
right = box * 1
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordNear.png', 'png')

#Not
box = 24 #pixels
left = box * 1
top = box * 33
right = box * 2
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordNot.png', 'png')

#Ok
box = 24 #pixels
left = box * 2
top = box * 33
right = box * 3
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordOk.png', 'png')

#On
box = 24 #pixels
left = box * 3
top = box * 33
right = box * 4
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordOn.png', 'png')

#Orb
box = 24 #pixels
left = box * 4
top = box * 33
right = box * 5
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordOrb.png', 'png')

#Pillar
box = 24 #pixels
left = box * 5
top = box * 33
right = box * 6
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPillar.png', 'png')

#Pipe
box = 24 #pixels
left = box * 6
top = box * 33
right = box * 7
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPipe.png', 'png')

#Play
box = 24 #pixels
left = box * 7
top = box * 33
right = box * 8
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPlay.png', 'png')

#Powered
box = 24 #pixels
left = box * 8
top = box * 33
right = box * 9
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPowered.png', 'png')

#Reed
box = 24 #pixels
left = box * 9
top = box * 33
right = box * 10
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordReed.png', 'png')

#Robot
box = 24 #pixels
left = box * 10
top = box * 33
right = box * 11
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRobot.png', 'png')

#Rock
box = 24 #pixels
left = box * 11
top = box * 33
right = box * 12
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRock.png', 'png')

#Rocket
box = 24 #pixels
left = box * 12
top = box * 33
right = box * 13
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRocket.png', 'png')

#Rose
box = 24 #pixels
left = box * 13
top = box * 33
right = box * 14
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRose.png', 'png')

#Rubble
box = 24 #pixels
left = box * 14
top = box * 33
right = box * 15
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRubble.png', 'png')

#Shirt
box = 24 #pixels
left = box * 15
top = box * 33
right = box * 16
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordShirt.png', 'png')

#Skull
box = 24 #pixels
left = box * 16
top = box * 33
right = box * 17
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSkull.png', 'png')

#Spike
box = 24 #pixels
left = box * 17
top = box * 33
right = box * 18
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSpike.png', 'png')

#Star
box = 24 #pixels
left = box * 18
top = box * 33
right = box * 19
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordStar.png', 'png')

#Statue
box = 24 #pixels
left = box * 19
top = box * 33
right = box * 20
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordStatue.png', 'png')

#Stump
box = 24 #pixels
left = box * 20
top = box * 33
right = box * 21
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordStump.png', 'png')

#Text
box = 24 #pixels
left = box * 21
top = box * 33
right = box * 22
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordText.png', 'png')

#Tile
box = 24 #pixels
left = box * 22
top = box * 33
right = box * 23
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordTile.png', 'png')

#Tree
box = 24 #pixels
left = box * 23
top = box * 33
right = box * 24
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordTree.png', 'png')

#Sun
box = 24 #pixels
left = box * 24
top = box * 33
right = box * 25
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSun.png', 'png')

#Ufo
box = 24 #pixels
left = box * 25
top = box * 33
right = box * 26
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordUfo.png', 'png')

#Violet
box = 24 #pixels
left = box * 26
top = box * 33
right = box * 27
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordViolet.png', 'png')

#Wall
box = 24 #pixels
left = box * 27
top = box * 33
right = box * 28
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWall.png', 'png')

#Water
box = 24 #pixels
left = box * 28
top = box * 33
right = box * 29
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWater.png', 'png')

#Without
box = 24 #pixels
left = box * 29
top = box * 33
right = box * 30
bottom = box * 34
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWithout.png', 'png')

#A
box = 24 #pixels
left = box * 0
top = box * 36
right = box * 1
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordA.png', 'png')

#B
box = 24 #pixels
left = box * 1
top = box * 36
right = box * 2
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordB.png', 'png')

#C
box = 24 #pixels
left = box * 2
top = box * 36
right = box * 3
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordC.png', 'png')

#D
box = 24 #pixels
left = box * 3
top = box * 36
right = box * 4
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordD.png', 'png')

#E
box = 24 #pixels
left = box * 4
top = box * 36
right = box * 5
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordE.png', 'png')

#F
box = 24 #pixels
left = box * 5
top = box * 36
right = box * 6
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordF.png', 'png')

#G
box = 24 #pixels
left = box * 6
top = box * 36
right = box * 7
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordG.png', 'png')

#H
box = 24 #pixels
left = box * 7
top = box * 36
right = box * 8
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordH.png', 'png')

#I
box = 24 #pixels
left = box * 8
top = box * 36
right = box * 9
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordI.png', 'png')

#L
box = 24 #pixels
left = box * 9
top = box * 36
right = box * 10
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordL.png', 'png')

#M
box = 24 #pixels
left = box * 10
top = box * 36
right = box * 11
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordM.png', 'png')

#N
box = 24 #pixels
left = box * 11
top = box * 36
right = box * 12
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordN.png', 'png')

#O
box = 24 #pixels
left = box * 12
top = box * 36
right = box * 13
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordO.png', 'png')

#R
box = 24 #pixels
left = box * 13
top = box * 36
right = box * 14
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordR.png', 'png')

#S
box = 24 #pixels
left = box * 14
top = box * 36
right = box * 15
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordS.png', 'png')

#T
box = 24 #pixels
left = box * 15
top = box * 36
right = box * 16
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordT.png', 'png')

#U
box = 24 #pixels
left = box * 16
top = box * 36
right = box * 17
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordU.png', 'png')

#V
box = 24 #pixels
left = box * 17
top = box * 36
right = box * 18
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordV.png', 'png')

#W
box = 24 #pixels
left = box * 18
top = box * 36
right = box * 19
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordW.png', 'png')

#X
box = 24 #pixels
left = box * 19
top = box * 36
right = box * 20
bottom = box * 37
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordX.png', 'png')

#Enter
box = 24 #pixels
left = box * 20
top = box * 36
right = box * 21
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordEnter.png', 'png')

#Menu
box = 24 #pixels
left = box * 22
top = box * 36
right = box * 23
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMenu.png', 'png')

#Move
box = 24 #pixels
left = box * 24
top = box * 36
right = box * 25
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMove.png', 'png')

#Restart
box = 24 #pixels
left = box * 26
top = box * 36
right = box * 27
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRestart.png', 'png')

#Undo
box = 24 #pixels
left = box * 28
top = box * 36
right = box * 29
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordUndo.png', 'png')

#Wait
box = 24 #pixels
left = box * 30
top = box * 36
right = box * 31
bottom = box * 37

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWait.png', 'png')

#Back
box = 24 #pixels
left = box * 0
top = box * 39
right = box * 1
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBack.png', 'png')

#Best
box = 24 #pixels
left = box * 1
top = box * 39
right = box * 2
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBest.png', 'png')

#Blue
box = 24 #pixels
left = box * 2
top = box * 39
right = box * 3
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBlue.png', 'png')

#Bonus
box = 24 #pixels
left = box * 3
top = box * 39
right = box * 4
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordBonus.png', 'png')

#Chill
box = 24 #pixels
left = box * 4
top = box * 39
right = box * 5
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordChill.png', 'png')

#Defeat
box = 24 #pixels
left = box * 5
top = box * 39
right = box * 6
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDefeat.png', 'png')

#Done
box = 24 #pixels
left = box * 6
top = box * 39
right = box * 7
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDone.png', 'png')

#Down
box = 24 #pixels
left = box * 7
top = box * 39
right = box * 8
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordDown.png', 'png')

#End
box = 24 #pixels
left = box * 8
top = box * 39
right = box * 9
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordEnd.png', 'png')

#Fall
box = 24 #pixels
left = box * 9
top = box * 39
right = box * 10
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFall.png', 'png')

#Float
box = 24 #pixels
left = box * 10
top = box * 39
right = box * 11
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordFloat.png', 'png')

#Hide
box = 24 #pixels
left = box * 11
top = box * 39
right = box * 12
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHide.png', 'png')

#Hot
box = 24 #pixels
left = box * 12
top = box * 39
right = box * 13
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordHot.png', 'png')

# Left
box = 24 #pixels
left = box * 13
top = box * 39
right = box * 14
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLeft.png', 'png')

#Melt
box = 24 #pixels
left = box * 14
top = box * 39
right = box * 15
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMelt.png', 'png')

#More
box = 24 #pixels
left = box * 15
top = box * 39
right = box * 16
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMore.png', 'png')

#Move
box = 24 #pixels
left = box * 16
top = box * 39
right = box * 17
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMove.png', 'png')

#Open
box = 24 #pixels
left = box * 17
top = box * 39
right = box * 18
bottom = box * 40
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordOpen.png', 'png')

#Aloita
box = 24 #pixels
left = box * 20
top = box * 39
right = box * 21
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordAloita.png', 'png')

#Menuun
box = 24 #pixels
left = box * 22
top = box * 39
right = box * 23
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordMenuun.png', 'png')

#Liiku
box = 24 #pixels
left = box * 24
top = box * 39
right = box * 25
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordLiiku.png', 'png')

#Uusiksi
box = 24 #pixels
left = box * 26
top = box * 39
right = box * 27
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordUusiksi.png', 'png')

#Peruuta
box = 24 #pixels
left = box * 28
top = box * 39
right = box * 29
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPeruuta.png', 'png')

#Odota
box = 24 #pixels
left = box * 30
top = box * 39
right = box * 31
bottom = box * 40

counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  for i in range(2):
    sprite = sheet.crop((left, top, right, bottom))
    left = left + box
    right = right + box

    counter +=1
    name = basename % counter
    sprite.save(name)
    j += 1
  left = 0
  right = box
  top = top + box
  bottom = bottom + box
  i+=1

fullSprite = Image.new('RGBA', (3*box, 2*box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordOdota.png', 'png')

#Power
box = 24 #pixels
left = box * 0
top = box * 42
right = box * 1
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPower.png', 'png')

#Pull
box = 24 #pixels
left = box * 1
top = box * 42
right = box * 2
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPull.png', 'png')

#Push
box = 24 #pixels
left = box * 2
top = box * 42
right = box * 3
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordPush.png', 'png')

#Red
box = 24 #pixels
left = box * 3
top = box * 42
right = box * 4
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRed.png', 'png')

#Right
box = 24 #pixels
left = box * 4
top = box * 42
right = box * 5
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordRight.png', 'png')

#Sad
box = 24 #pixels
left = box * 5
top = box * 42
right = box * 6
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSad.png', 'png')

#Safe
box = 24 #pixels
left = box * 6
top = box * 42
right = box * 7
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSafe.png', 'png')

#Shift
box = 24 #pixels
left = box * 7
top = box * 42
right = box * 8
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordShift.png', 'png')

#Shut
box = 24 #pixels
left = box * 8
top = box * 42
right = box * 9
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordShut.png', 'png')

#Sink
box = 24 #pixels
left = box * 9
top = box * 42
right = box * 10
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSink.png', 'png')

#Sleep
box = 24 #pixels
left = box * 10
top = box * 42
right = box * 11
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSleep.png', 'png')

#Stick
box = 24 #pixels
left = box * 11
top = box * 42
right = box * 12
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordStick.png', 'png')

#Stop
box = 24 #pixels
left = box * 12
top = box * 42
right = box * 13
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordStop.png', 'png')

#Swap
box = 24 #pixels
left = box * 13
top = box * 42
right = box * 14
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordSwap.png', 'png')

#Tele
box = 24 #pixels
left = box * 14
top = box * 42
right = box * 15
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordTele.png', 'png')

#Up
box = 24 #pixels
left = box * 15
top = box * 42
right = box * 16
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordUp.png', 'png')

#Wake
box = 24 #pixels
left = box * 16
top = box * 42
right = box * 17
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWake.png', 'png')

#Win
box = 24 #pixels
left = box * 17
top = box * 42
right = box * 18
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWin.png', 'png')

#Wonder
box = 24 #pixels
left = box * 18
top = box * 42
right = box * 19
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWonder.png', 'png')

#Word
box = 24 #pixels
left = box * 19
top = box * 42
right = box * 20
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordWord.png', 'png')

#You
box = 24 #pixels
left = box * 20
top = box * 42
right = box * 21
bottom = box * 43
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wordYou.png', 'png')

#Wall Tile
box = 24 #pixels
left = box * 0
top = box * 57
right = box * 1
bottom = box * 58
basename = 'sprite_%d.png'

sprite = sheet.crop((left, top, right, bottom))
name = basename % counter
sprite.save(name)

fullSprite = Image.new('RGBA', (box, box))
for i in range(1):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('wallTile.png', 'png')

#water
box = 24 #pixels
left = box * 15
top = box * 54
right = box * 16
bottom = box * 55
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('water.png', 'png')

#Lava
box = 24 #pixels
left = box * 16
top = box * 57
right = box * 17
bottom = box * 58
counter = 0
basename = 'sprite_%d.png'

for j in range(3):
  sprite = sheet.crop((left, top, right, bottom))
  top = top + box
  bottom = bottom + box
  counter +=1
  name = basename % counter
  sprite.save(name)
  j += 1

fullSprite = Image.new('RGBA', (3*box, box))
for i in range(3):
  i += 1
  fullSprite.paste(Image.open('sprite_'+ str(i) + '.png'),(0 + ((i*box) - box), 0))
fullSprite.save('Lava.png', 'png')

# #cuts out boxes left to right first
# box = 24 #pixels
# left = 0
# top = 0
# right = box
# bottom = box

# counter = 0
# basename = 'sprite_%d.png'

# for j in range(3):
#   for i in range(5):
#     sprite = sheet.crop((left, top, right, bottom))
#     left = left + box
#     right = right + box

#     counter +=1
#     name = basename % counter
#     sprite.save(name)
#     print("Wrote %s" % name)
#     j += 1
#   left = 0
#   right = box
#   top = top + box
#   bottom = bottom + box
#   i+=1

# #to cut out negative space sprites
# def sprite_mask(img, bg_point=(0, 0)):
#     width, height = img.size
#     im = img.load()

#     bg = im[bg_point]
#     mask_img = Image.new('L', img.size)
#     mask = mask_img.load()
#     for x in range(width):
#         for y in range(height):
#             if im[x, y] != bg:
#                 mask[x, y] = 255
#     return mask_img, bg

# #to cut out negative space sprites

# import sys
# import numpy
# from scipy.ndimage import label, morphology

# def split_sprite(img, mask, bg, join_interior=True, basename='sprite_%d.png'):
#     im = img.load()

#     m = numpy.array(mask, dtype=numpy.uint8)
#     if join_interior:
#         m = morphology.binary_fill_holes(m)
#     lbl, ncc = label(m, numpy.ones((3, 3)))

#     for i in range(1, ncc + 1):
#         px, py = numpy.nonzero(lbl == i)
#         xmin, xmax, ymin, ymax = px.min(), px.max(), py.min(), py.max()

#         sprite = Image.new(img.mode, (ymax - ymin + 1, xmax - xmin + 1), bg)
#         sp = sprite.load()
#         for x, y in zip(px, py):
#             x, y = int(x), int(y)
#             sp[y - int(ymin), x - int(xmin)] = im[y, x]

#         name = basename % i
#         sprite.save(name)
#         print("Wrote %s" % name)

# sprite = Image.open('babaSheet.png')
# mask, bg = sprite_mask(sprite)
# split_sprite(sprite, mask, bg)